/*
 * Copyright 2014 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.psdatalib.pstags;

  import com.powersurgepub.psdatalib.ui.*;
  import com.powersurgepub.psutils.*;

/**
 A Preferences pane used to identify tags to select, and tags to suppress. 

 @author Herb Bowie
 */
public class TagsPrefs 
    extends javax.swing.JPanel {
  
  private static final String SELECT_TAGS    = "select-tags";
  private static final String SUPPRESS_TAGS  = "suppress-tags";
  
  private TextSelector  selectTextSelector;
  private TextSelector  suppressTextSelector;

  /**
   Creates new form TagsPrefs
   */
  public TagsPrefs() {
    initComponents();
        java.awt.GridBagConstraints gridBagConstraints;
    
    selectTextSelector = new TextSelector();
    selectTextSelector.setEditable(true);
    selectTextSelector.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        UserPrefs.getShared().setPref
            (SELECT_TAGS, selectTextSelector.getText());
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    this.add(selectTextSelector, gridBagConstraints);
    
    suppressTextSelector = new TextSelector();
    suppressTextSelector.setEditable(true);
    suppressTextSelector.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        UserPrefs.getShared().setPref
            (SUPPRESS_TAGS, suppressTextSelector.getText());
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    this.add(suppressTextSelector, gridBagConstraints);
    
    selectTextSelector.setText
        (UserPrefs.getShared().getPref (SELECT_TAGS, ""));
    suppressTextSelector.setText
        (UserPrefs.getShared().getPref (SUPPRESS_TAGS, ""));
  }
  
  public void setTagsValueList (ValueList valueList) {
    selectTextSelector.setValueList (valueList);
    suppressTextSelector.setValueList(valueList);
  }
  
  public String getSelectTagsAsString() {
    return selectTextSelector.getText();
  }
  
  public String getSuppressTagsAsString() {
    return suppressTextSelector.getText();
  }
  
  public void savePrefs() {
    UserPrefs.getShared().setPref
        (SELECT_TAGS, selectTextSelector.getText());
    UserPrefs.getShared().setPref
        (SUPPRESS_TAGS, suppressTextSelector.getText());
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    tagsSelectLabel = new javax.swing.JLabel();
    tagsSuppressLabel = new javax.swing.JLabel();

    setLayout(new java.awt.GridBagLayout());

    tagsSelectLabel.setText("Tags to Select:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(tagsSelectLabel, gridBagConstraints);

    tagsSuppressLabel.setText("Tags to Suppress:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.ipadx = 2;
    gridBagConstraints.ipady = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    add(tagsSuppressLabel, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel tagsSelectLabel;
  private javax.swing.JLabel tagsSuppressLabel;
  // End of variables declaration//GEN-END:variables
}
