/*
 * Copyright 1999 - 2013 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.psdatalib.ui;

  import java.awt.*;
  import javax.swing.*;

/**
   A panel allowing the user to make a binary (yes/no) decision. <p>
     
   This code is copyright (c) 2003 by Herb Bowie of PowerSurge Publishing. 
   All rights reserved. <p>
   
   Version History: <ul><li>
      2003/10/22 - Initially written for Two Due project.<li>
      </ul>
   @author Herb Bowie (<a href="mailto:herb@powersurgepub.com">
           herb@powersurgepub.com</a>)<br>
           of PowerSurge Publishing (<A href="http://www.powersurgepub.com">
           www.powersurgepub.com</a>)
   @version 2003/11/15 - Move to ui package.
 */
public class BinaryPanel 
    extends javax.swing.JPanel {
      
  private JLabel        binaryLabel;
  private ButtonGroup   group         = new ButtonGroup();
  private JRadioButton  button1;
  private JRadioButton  button2;
  
  // private String        labelPosition;
  // private String        button1Position = BorderLayout.CENTER;
  // private String        button2Position;
  
  /** Creates new form BinaryPanel */
  public BinaryPanel
      (String label, String button1Name, String button2Name, boolean horizontal) {
        
    initComponents();
    
    /*
     if (horizontal) {
      labelPosition = BorderLayout.WEST;
      button2Position = BorderLayout.EAST;
    } else {
      labelPosition = BorderLayout.NORTH;
      button2Position = BorderLayout.SOUTH;
    } */
    
    if (label != null && label.length() > 0) {
      binaryLabel = new JLabel (label);
      add (binaryLabel);
    }
    
    button1 = new JRadioButton (button1Name);
    button1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button1ActionPerformed(evt);
      }
    });
    button1.setSelected (true);
    add (button1);
    group.add (button1);
    
    button2 = new JRadioButton (button2Name);
    button2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        button2ActionPerformed(evt);
      }
    });
    add (button2);
    group.add (button2);  
    
  }
  
  public void button1ActionPerformed(java.awt.event.ActionEvent evt) {
    
  }
  
  public void button2ActionPerformed(java.awt.event.ActionEvent evt) {
    
  }
  
  public void setDecision (String s) {
    if (s.equalsIgnoreCase (button2.getText())) {
      button2.setSelected(true);
    } else {
      button1.setSelected(true);
    }
  }
  
  public void setDecision (int d) {
    if (d > 1) {
      button2.setSelected(true);
    } else {
      button1.setSelected(true);
    }
  }
  
  public String getDecisionString () {
    if (button1.isSelected()) {
      return button1.getText();
    } else {
      return button2.getText();
    }
  }
  
  public int getDecision () {
    if (button1.isSelected()) {
      return 1;
    } else {
      return 2;
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4));
    }// </editor-fold>//GEN-END:initComponents
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
  
}
