/*
 * Copyright 2013 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.psdatalib.ui;

  import com.powersurgepub.psutils.*;
  import javax.swing.*;

/**
 A panel that can serve as a label for a hyperlink, while also offering some
 associated capabilities made available via buttons. 

 @author Herb Bowie
 */
public class LinkLabel 
    extends JPanel {

  private JTextArea             linkText = null;
  private LinkTweakerInterface  linkTweaker = null;

  /**
   Creates new form LinkLabel
   */
  public LinkLabel() {
    initComponents();
  }
  
  public LinkLabel (String labelText) {
    initComponents();
    linkLabel.setText(labelText);
  }
  
  public void setLabelText (String labelText) {
    linkLabel.setText(labelText);
  }
  
  public String getLabelText() {
    return linkLabel.getText();
  }
  
  public void setLinkTextArea (JTextArea linkText) {
    this.linkText = linkText;
    linkLabel.setLabelFor(linkText);
  }
  
  public void setLinkTweaker (LinkTweakerInterface linkTweaker) {
    this.linkTweaker = linkTweaker;
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    linkLabel = new javax.swing.JLabel();
    urlLaunchButton = new javax.swing.JButton();
    tweakButton = new javax.swing.JButton();
    filler = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder());
    setLayout(new java.awt.GridBagLayout());

    linkLabel.setText("Link");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(8, 8, 4, 4);
    add(linkLabel, gridBagConstraints);

    urlLaunchButton.setBackground(new java.awt.Color(51, 51, 51));
    urlLaunchButton.setFont(new java.awt.Font("Zapf Dingbats", 0, 13)); // NOI18N
    urlLaunchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/powersurgepub/psdatalib/ui/right-arrow.png"))); // NOI18N
    urlLaunchButton.setToolTipText("Open the URL in your Web browser");
    urlLaunchButton.setBorderPainted(false);
    urlLaunchButton.setContentAreaFilled(false);
    urlLaunchButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    urlLaunchButton.setIconTextGap(0);
    urlLaunchButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    urlLaunchButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        urlLaunchButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 0);
    add(urlLaunchButton, gridBagConstraints);

    tweakButton.setText("Tweak");
    tweakButton.setToolTipText("Click here to tweak the link.");
    tweakButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
    tweakButton.setMaximumSize(new java.awt.Dimension(120, 24));
    tweakButton.setMinimumSize(new java.awt.Dimension(70, 24));
    tweakButton.setPreferredSize(new java.awt.Dimension(70, 24));
    tweakButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tweakButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 4);
    add(tweakButton, gridBagConstraints);

    filler.setFont(new java.awt.Font("Arial", 0, 3)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(filler, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void urlLaunchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlLaunchButtonActionPerformed
    if (linkText != null) {
      Home.getShared().openURL(linkText.getText());
    }
  }//GEN-LAST:event_urlLaunchButtonActionPerformed

  private void tweakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tweakButtonActionPerformed

    if (linkText != null
        && linkText.getText().length() > 0
        && linkTweaker != null
        && linkTweaker instanceof WindowToManage) {
      linkTweaker.setLink(linkText.getText(), linkLabel.getText());
      linkTweaker.setLocation(
        this.getX() + 60,
        this.getY() + 60);
      WindowToManage linkTweakerWindow = (WindowToManage)linkTweaker;
      WindowMenuManager.getShared().makeVisible(linkTweakerWindow);
    }

  }//GEN-LAST:event_tweakButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel filler;
  private javax.swing.JLabel linkLabel;
  private javax.swing.JButton tweakButton;
  private javax.swing.JButton urlLaunchButton;
  // End of variables declaration//GEN-END:variables
}
