/*
 * Copyright 1999 - 2013 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.psdatalib.ui;

  import com.powersurgepub.psutils.*;
  import java.text.*;
  import java.util.*;

/**
 Define a standard status bar to go at the bottom of a window. 

 @author Herb Bowie
 */
public class StatusBar 
    extends javax.swing.JPanel {
  
    private DateFormat    longDateFormatter
      = new SimpleDateFormat ("EEEE MMMM d, yyyy");

  /** Creates new form StatusBar */
  public StatusBar() {
    initComponents();
  }
  
  public void setFileName (FileName fileName) {
    setFileName (fileName.getToFit(30), fileName.toString());
  }
  
  public void setFileName (String shortName, String longName) {
    fileNameLabel.setText (shortName);
    fileNameLabel.setToolTipText(longName);
  }
  
  public void setPosition(int position, int size) {
    indexLabel.setText(String.valueOf(position));
    ofLabel.setText("of");
    sizeLabel.setText(String.valueOf(size));
  }
  
  public void setStatus (String briefStatus) {
    statusLabel.setText(briefStatus);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileNameLabel = new javax.swing.JLabel();
        dividerLabel1 = new javax.swing.JLabel();
        indexLabel = new javax.swing.JLabel();
        ofLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        dividerLabel2 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        fileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fileNameLabel.setMaximumSize(new java.awt.Dimension(400, 40));
        fileNameLabel.setMinimumSize(new java.awt.Dimension(100, 14));
        fileNameLabel.setPreferredSize(new java.awt.Dimension(200, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(fileNameLabel, gridBagConstraints);

        dividerLabel1.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 8, 2, 8);
        add(dividerLabel1, gridBagConstraints);

        indexLabel.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(indexLabel, gridBagConstraints);

        ofLabel.setText("of");
        ofLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(ofLabel, gridBagConstraints);

        sizeLabel.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(sizeLabel, gridBagConstraints);

        dividerLabel2.setText("|");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 8, 2, 8);
        add(dividerLabel2, gridBagConstraints);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setMaximumSize(new java.awt.Dimension(400, 40));
        statusLabel.setMinimumSize(new java.awt.Dimension(100, 14));
        statusLabel.setPreferredSize(new java.awt.Dimension(200, 18));
        statusLabel.setText (longDateFormatter.format (new Date()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 22);
        add(statusLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dividerLabel1;
    private javax.swing.JLabel dividerLabel2;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JLabel ofLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
